developer-student-club-thapar/buying_selling_devops

- .prettierignore
- .prettierrc.js
- CONTRIBUTION.md
- src/App.js
- src/index.js
- src/pages/PrivateTest.js
- src/pages/test.js
- src/routes/Route.js
- src/routes/index.js
- src/services/history.js
Added the ```.prettierignore``` file and ```.prettierrc.js``` file. Fixes #3
> Prettier config

- buying_selling/settings.py
- buying_selling/urls.py
- package.json
- poetry.lock
- pyproject.toml
- users/views.py
- yarn.lock
> setup oauth

- package.json
- src/index.js
- src/redux/actions/authActions.js
- src/redux/actions/index.js
- src/redux/reducers/authReducer.js
- src/redux/reducers/index.js
- src/redux/store/index.js
- yarn.lock
> redux boilerplate

- buying_selling/jwt_settings.py
- buying_selling/settings.py
- buying_selling/urls.py
- src/components/GoogleLoginButton.js
- users/views.py
Did a few things:
- Added a JWT Refresh Token route to get new `access tokens`
- Created a test `HelloView` route to check token management during development
- Tweaked `JWT Settings` for better security and token expiration timings
- Changed frontend request url for authentication
> Refresh token configs

- posts/admin.py
> Added inline support for Post Model in admin panel

- src/App.js
- src/components/GoogleLoginButton.js
- src/pages/Login.js
- src/pages/Welcome.js
- src/redux/actions/authActions.js
- src/redux/reducers/authReducer.js
- src/redux/types.js
> Did some error handling

- package.json
- src/App.css
- src/components/Product/ImageCarousel.js
- src/styles/Product.module.css
- yarn.lock
> carousel fix

- client-wrapper/server.js
- package.json
Just did a basic express setup for out client wrapper.
> [Done] setup express basic

- CODE_OF_CONDUCT.md
> fix linting

- buying_selling/config/settings.py
- buying_selling/posts/api/permissions.py
- buying_selling/posts/api/views.py
- buying_selling/users/api/permissions.py
- buying_selling/users/api/views.py
Refactored the `SIGNING_KEY` extraction and a setting in `settings.py`
@Saurav-Shrivastav can u test it locally to see if the JWT process is still intact and not broken
> a bit of refactoring

- buying_selling/config/settings.py
- buying_selling/posts/api/permissions.py
- buying_selling/posts/api/serializers.py
- buying_selling/posts/api/urls.py
- buying_selling/posts/api/views.py
- buying_selling/users/api/permissions.py
- setup.cfg
- src/redux/actions/authActions.js
- Shifted to Model View Sets
- Add Partial Update Support
- Use DRF Routers for navigation
@Saurav-Shrivastav Kindly go through the changes once, I have tested them extensively on my side. Still check them once on ur side. Also, now are url patterns have changes
- For list view it's `/api/posts/`
- For create view it's `/api/posts/`
- For detail view it's `/api/posts/<pk>/`
- For update and partial update it's `/api/posts/<pk>/`
- For delete it's `/api/posts/<pk>/`
- For myposts it's `/api/posts/manage/myposts/`
> improvise views, url management, add partial update support

- buying_selling/posts/api/serializers.py
- buying_selling/posts/api/views.py
This fixes #74 
PostDetailAPIView now returns Images related to the post along with other details.
> [WIP] Updated the viewset and added the Image serializer

- buying_selling/posts/api/serializers.py
- buying_selling/posts/api/urls.py
- buying_selling/posts/api/views.py
- Can be accessed at - /api/posts/categories/
> Added a route to fetch all categories

- buying_selling/posts/api/serializers.py
- buying_selling/posts/api/views.py
> [Done] Added the image field in list all posts route

- buying_selling/config/settings.py
- buying_selling/posts/api/views.py
Going to add
- Basic Filtering on basis of isSold, onDiscount, category, condition [Done]
- Advanced Filtering on Search query with product name, brand [Done]
- Ordering Queries on basis of datePosted, discount, price [Done]
Edit: I think we can also add range filtering [Pending]
> [Done] Filtering Backend Routes for GET posts

- buying_selling/posts/api/serializers.py
added "brand" field in PostListSerializer
> added brand field

- buying_selling/posts/api/serializers.py
This fixes #118 
- Get all Posts and List all posts route now returns a list of `Category` objects.
> [WIP] Returning list of category objects

- buying_selling/config/settings.py
- buying_selling/config/urls.py
- poetry.lock
- pyproject.toml
This fixes #53 
- The documentation can be accessed at `/admin/doc/`
> Documentation for admin panel created

- buying_selling/users/api/urls.py
- buying_selling/users/api/views.py
This fixes #86 
- Can be accessed by logged in users at ```/api/users/hostels/```
> Get all hostels route ready

- buying_selling/posts/api/serializers.py
> PostDetailSerializer now returns complete condition and age

- buying_selling/posts/api/permissions.py
- buying_selling/posts/api/serializers.py
- buying_selling/posts/api/views.py
- The disabled posts can be accessed only by the author at the following endpoints - 
1. `api/posts/manage/myposts`
2. `api/posts/<post-id>/`
- The disabled posts will not be shown at the `api/posts/` (list view) endpoint.
> Working with Disabled Posts
